"""add duplicate_dismissals jsonb

Revision ID: 4b419de75929
Revises: 970d3f2a6c07
Create Date: 2026-05-14 12:48:43.619980

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b419de75929"
down_revision: str | Sequence[str] | None = "970d3f2a6c07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column(
            "duplicate_dismissals",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "duplicate_dismissals")
    # ### end Alembic commands ###
