"""add line_items jsonb to extractions

Revision ID: 74d06e0c35fc
Revises: 4b419de75929
Create Date: 2026-05-14 16:33:54.767532

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74d06e0c35fc"
down_revision: str | Sequence[str] | None = "4b419de75929"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default lets existing rows backfill safely under the NOT NULL.
    op.add_column(
        "extractions",
        sa.Column(
            "line_items",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extractions", "line_items")
    # ### end Alembic commands ###
